### ISSUE TITLE
Q: Compatibility with Terraform v0.12

### ISSUE THREAD

**Issue by ArieHein** [raul-arrieta/Terraform-Outputs#2]
From the code, there doesn't seem to be dependency on the terraform version, but have you tested it with 0.12 yet ?

**Comment by raul-arrieta** [comment]
Hi @ArieHein,
I just tested version 0.12.1 and it seems to work properly.

![image](https://user-images.githubusercontent.com/10473782/59228658-afcaa180-8bd8-11e9-808d-ef4702b23b2b.png)

**Comment by joseph-passineau** [comment]
Same here. Tested with version v0.12.3 and it works fine.
